# Generated by Django 3.2.9 on 2021-12-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20211201_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
